{% set name = "bluez" %}
{% set version = "5.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.kernel.org/pub/linux/bluetooth/{{ name }}-{{ version }}.tar.xz
  sha256: 5ffcaae18bbb6155f1591be8c24898dc12f062075a40b538b745bfd477481911

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - dbus
    - readline
  run:
    - readline

test:
  commands:
    - bluetoothctl --help

about:
  home: http://www.bluez.org/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'BlueZ - Bluetooth protocol stack for Linux'
  description: |
    The Bluetooth wireless technology is a worldwide specification for a 
    small-form factor, low-cost radio solution that provides links between 
    mobile computers, mobile phones, other portable handheld devices, 
    and connectivity to the Internet. The specification is developed, 
    published and promoted by the Bluetooth Special Interest Group (SIG).
  doc_url: http://www.bluez.org/about/
  dev_url: http://www.bluez.org/development/

extra:
  recipe-maintainers:
    - xmnlab
