{% set name = "kudu-cpp" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/kudu/archive/{{ version }}.tar.gz
  sha256: 0ff304009606a28101f10010fb0b02d5e8f7e7254892468ca8d1d3624ba44672

build:
  number: 0
  skip: True  # [win]
  # script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('c++') }}
    - autoconf
    - automake
    - curl
    - flex
    - git
    - make
    - openjdk 8.*
    - patch
    - pkg-config
    - rsync
    - unzip
  host:
    - openssl
    - python
    - krb5
    - ntplib
    - sasl
  run:
    - python

test:
  imports:
    - simplejson
    - simplejson.tests

about:
  home: https://kudu.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Apache Kudu completes Hadoop storage layer to enable fast analytics on fast data.'
  description: |
    Kudu provides a combination of fast inserts/updates and efficient columnar 
    scans to enable multiple real-time analytic workloads across a single storage 
    layer. As a new complement to HDFS and Apache HBase, Kudu gives architects 
    the flexibility to address a wider variety of use cases without exotic workarounds.
  doc_url: https://kudu.apache.org/docs/
  dev_url: https://github.com/apache/kudu

extra:
  recipe-maintainers:
    - xmnlab
